#!/bin/bash
# Example: Complete Audit Workflow
# This script demonstrates a full audit cycle with result processing

set -e

echo "🚀 Starting Complete Audit Workflow Example"
echo "=========================================="

# 1. Run different types of audits
echo "📋 Step 1: Running Audits..."

echo "  - Codebase audit (TODOs and imports)"
autonomous-auditor --mode codebase_auditor "Find all TODO comments and imports" --format json --out example-todos.json

echo "  - Config security audit"  
autonomous-auditor --mode config_inspector "Check for security issues" --format json --out example-security.json

echo "  - Repository hygiene audit"
autonomous-auditor --mode repo_hygiene "Check repository structure" --format json --out example-hygiene.json

# 2. Analyze results
echo ""
echo "📊 Step 2: Analyzing Results..."

echo "  - TODO Analysis:"
TODO_COUNT=$(cat example-todos.json | jq -r '.result' | grep -c "TODO" || echo "0")
echo "    Found $TODO_COUNT TODO comments"

echo "  - Security Analysis:"
SECURITY_STATUS=$(cat example-security.json | jq -r '.status')
echo "    Security audit status: $SECURITY_STATUS"

echo "  - Hygiene Analysis:"
HYGIENE_STATUS=$(cat example-hygiene.json | jq -r '.status')
echo "    Hygiene audit status: $HYGIENE_STATUS"

# 3. Apply policies
echo ""
echo "📋 Step 3: Policy Enforcement..."

echo "  - Applying SOC2 policy to TODO results:"
audit-policy example-todos.json --pack soc2 || echo "    Policy violations found"

echo "  - Applying GDPR policy to security results (dry-run):"
audit-policy example-security.json --pack gdpr --dry-run

# 4. Generate reports
echo ""
echo "📄 Step 4: Generating Reports..."

# Create summary report
cat > example-audit-summary.md << EOF
# Audit Summary Report - $(date)

## Overview
- **Date**: $(date)
- **Repository**: $(basename $(pwd))
- **Auditor Version**: v1.1.0

## Results Summary
| Audit Type | Status | Key Findings |
|------------|--------|--------------|
| Codebase | $TODO_COUNT TODOs | $(cat example-todos.json | jq -r '.status') |
| Security | Config Check | $SECURITY_STATUS |
| Hygiene | Structure Check | $HYGIENE_STATUS |

## Detailed Findings

### TODO Comments Found
\`\`\`
$(cat example-todos.json | jq -r '.result' | head -10)
\`\`\`

### Policy Compliance
- SOC2 Status: $(audit-policy example-todos.json --pack soc2 --format json 2>/dev/null | jq -r '.status' || echo "violations found")
- GDPR Status: $(audit-policy example-security.json --pack gdpr --dry-run --format json 2>/dev/null | jq -r '.status' || echo "needs review")

## Recommendations
1. Address TODO comments to reduce technical debt
2. Review security configurations
3. Ensure repository hygiene standards
4. Implement continuous compliance monitoring

---
*Generated by Autonomous Auditor v1.1.0*
EOF

echo "  - Summary report created: example-audit-summary.md"

# 5. Generate compliance evidence
echo "  - Generating compliance evidence..."
audit-policy example-hygiene.json --pack soc2 --evidence > example-soc2-evidence.txt 2>/dev/null || echo "    Evidence generation completed with notes"

# 6. Create CI-ready script
cat > example-ci-check.sh << 'EOF'
#!/bin/bash
# CI Integration Example
# Use this in your CI/CD pipeline

# Run audit
autonomous-auditor --mode repo_hygiene "CI audit" --format json --out ci-audit.json

# Check results
STATUS=$(cat ci-audit.json | jq -r '.status')
if [ "$STATUS" != "success" ]; then
    echo "❌ Audit failed"
    exit 1
fi

# Apply policy (customize as needed)
audit-policy ci-audit.json --pack soc2

# Success
echo "✅ All checks passed"
EOF

chmod +x example-ci-check.sh
echo "  - CI integration script created: example-ci-check.sh"

# 7. Show what was created
echo ""
echo "✅ Workflow Complete! Generated Files:"
echo "  📄 example-todos.json - Codebase audit results"
echo "  📄 example-security.json - Security audit results"  
echo "  📄 example-hygiene.json - Hygiene audit results"
echo "  📋 example-audit-summary.md - Executive summary report"
echo "  📜 example-soc2-evidence.txt - Compliance evidence"
echo "  🔧 example-ci-check.sh - CI integration script"

echo ""
echo "🎯 Next Steps:"
echo "  1. Review the audit summary: cat example-audit-summary.md"
echo "  2. Check policy compliance: audit-policy example-*.json --pack soc2"
echo "  3. Use CI script in your pipeline: ./example-ci-check.sh"
echo "  4. Archive results for compliance: mkdir audit-$(date +%Y%m%d) && mv example-* audit-$(date +%Y%m%d)/"

echo ""
echo "💡 Pro Tip: Run 'audit-policy example-todos.json --pack soc2 --explain' to understand policy rules"
